# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170813_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='tes', max_length=200),
            preserve_default=False,
        ),
    ]
