# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170905_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Can set book as returned'),)},
        ),
    ]
